# ============================================================================
# Kedro Parameters - Kedro 1.1.1 Compatible
# ============================================================================
# Pipeline parameters used across all nodes.
# See https://docs.kedro.org/en/stable/configuration/configuration.html

# Path to your raw input file (relative to project root)
data_path: "data/01_raw/data.csv"

# Data processing parameters
data_processing:
  test_size: 0.2
  random_state: 42
  handle_missing: true
  
# Model parameters
model:
  algorithm: "linear_regression"
  hyperparameters:
    fit_intercept: true
    
# Validation parameters
validation:
  cv_folds: 5
  scoring_metric: "r2"

# ============================================================================
# PHASE 2: Advanced Data Processing & Feature Engineering
# ============================================================================

# Missing Value Imputation Strategy
missing_value_strategy:
  method: "mean"                    # mean, median, forward_fill, knn
  knn_neighbors: 5
  forward_fill_limit: 3

# Feature Scaling Configuration
scaling:
  method: "standard"                # standard, minmax, robust
  with_mean: true
  with_std: true

# Feature Engineering Configuration
feature_engineering:
  create_polynomial: false
  polynomial_degree: 2
  create_interactions: false
  max_interactions: 10
  log_transform: false

# Feature Selection Configuration
feature_selection:
  method: "correlation"             # correlation, mutual_info, importance, rfe
  n_features: null
  threshold: 0.1
  top_n: 10
  importance_threshold: 0.01
