data_path: "data/01_raw/data.csv"

data_processing:
  test_size: 0.2
  random_state: 42
  handle_missing: "median"
  remove_duplicates: true

feature_engineering:
  scaling_method: "standard"
  feature_selection: false

algorithms:
  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    random_state: 42

evaluation:
  cv_folds: 5
  metrics:
    - accuracy
    - precision
    - recall
    - f1
