# ════════════════════════════════════════════════════════════════════════════
# PERFECT Phase 2 Parameters Configuration
# Complete parameter structure matching all pipeline expectations
# ════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────
# DATA PATHS (Required by Phase 1)
# ─────────────────────────────────────────────────────────────────────────────

data_path: "data/01_raw/data.csv"

# ─────────────────────────────────────────────────────────────────────────────
# DATA PROCESSING (Required by Phase 2 Feature Engineering)
# ─────────────────────────────────────────────────────────────────────────────

data_processing:
  handle_missing: "mean"              # Options: "mean", "median", "forward_fill", "drop"
  test_size: 0.2
  random_state: 42
  stratify: null                       # Set to target_column for stratified split

# ─────────────────────────────────────────────────────────────────────────────
# TARGET & FEATURES (Required by all phases)
# ─────────────────────────────────────────────────────────────────────────────

target_column: "Churn"                  # Column to predict
exclude_columns: []                    # Columns to exclude from features

# ─────────────────────────────────────────────────────────────────────────────
# FEATURE ENGINEERING (Phase 2)
# ─────────────────────────────────────────────────────────────────────────────

feature_engineering:
  polynomial_degree: 2
  include_bias: false
  max_output_features: 100             # Gap 3: Prevents feature explosion

# ─────────────────────────────────────────────────────────────────────────────
# CATEGORICAL HANDLING (Phase 2 - Gap 4)
# ─────────────────────────────────────────────────────────────────────────────

categorical:
  encoding_method: "onehot"            # Options: "onehot", "label", "target", "frequency"
  handle_unknown: "ignore"
  min_frequency: 1

# ─────────────────────────────────────────────────────────────────────────────
# SCALING & NORMALIZATION
# ─────────────────────────────────────────────────────────────────────────────

scaling:
  method: "standard"                   # Options: "standard", "minmax", "robust"

# ─────────────────────────────────────────────────────────────────────────────
# FEATURE SELECTION (Phase 2 - Gap 5: Real Target Importance)
# ─────────────────────────────────────────────────────────────────────────────

feature_selection:
  method: "importance"                 # Options: "variance", "correlation", "importance", "mutual_info"
  n_features: 10
  test_size: 0.2

# ─────────────────────────────────────────────────────────────────────────────
# PROBLEM TYPE DETECTION (Phase 2 - Gap 2)
# ─────────────────────────────────────────────────────────────────────────────

problem_type:
  auto_detect: true
  override: null                       # Set to "classification" or "regression" to override

# ─────────────────────────────────────────────────────────────────────────────
# VALIDATION (Phase 1)
# ─────────────────────────────────────────────────────────────────────────────

validation:
  check_missing: true
  check_duplicates: true
  check_data_types: true

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────────────────────

logging:
  verbose: true
  log_feature_importance: true
  log_problem_type: true
  log_preprocessing: true