# ============================================================================
# Kedro Parameters - Kedro 1.1.1 Compatible
# ============================================================================
# Pipeline parameters used across all nodes.
# See https://docs.kedro.org/en/stable/configuration/configuration.html

# Data processing parameters
data_processing:
  test_size: 0.2
  random_state: 42
  
# Feature engineering parameters
feature_engineering:
  scaling_method: "standard"
  feature_selection_method: "mutual_information"
  
# Model parameters
model:
  algorithm: "linear_regression"
  hyperparameters:
    fit_intercept: true
    
# Validation parameters
validation:
  cv_folds: 5
  scoring_metric: "r2"
