# Data Loading
data:
  raw_data_path: "data/01_raw/data.csv"
  test_size: 0.2
  random_state: 42
  stratify: null  # Set to target_column name if classification

# Target and Features
target_column: "col5"  # FIXED: Changed from 'target' to 'col5'
  # This is the column you're predicting
# If you want to predict a different column, change this!

# Feature Selection
feature_selection:
  method: "variance"  # Options: "variance", "correlation", "importance", "mutual_info"
  test_size: 0.2
  max_output_features: 100  # Prevents feature explosion (Gap 3)

# Categorical Encoding
categorical:
  encoding_method: "onehot"  # Options: "onehot", "label", "target", "frequency"
  handle_unknown: "ignore"

# Problem Type Detection
problem_type:
  auto_detect: true
  override: null  # Set to "classification" or "regression" to override auto-detection

# Polynomial Features (Feature Engineering)
polynomial:
  degree: 2
  include_bias: false

# Data Validation
validation:
  check_missing: true
  check_duplicates: true
  check_data_types: true

# Logging
logging:
  verbose: true
  log_feature_importance: true
  log_problem_type: true